global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 5s

  - job_name: "cub"
    static_configs:
      - targets: ["cub:80"]
    scrape_interval: 10s
    metrics_path: "/metrics"