logger:
  development: false
  stdout_only: false
  output_file: "/var/log/cub/cub.log"
  
  max_file_size_mb: 100
  max_backups_amount: 3
  max_file_age_days: 30
  compression: true
  
  time_key: "timestamp"
  level_key: "level"
  name_key: ""
  caller_key: "caller"
  message_key: "message"
  stacktrace_key: ""
  
  service: "cub"
  environment: "production"